"""Add AMDEC and Training tables

Revision ID: 8d7cd7c158ae
Revises: 
Create Date: 2025-12-04 11:21:27.450649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text
# revision identifiers, used by Alembic.
revision = '8d7cd7c158ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED', name='equipmentstatus'), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_equipment_designation'), 'equipment', ['designation'], unique=True)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('successful_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('error_messages', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_created_at'), 'import_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_logs_id'), 'import_logs', ['id'], unique=False)
    op.create_index(op.f('ix_import_logs_import_type'), 'import_logs', ['import_type'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('index_name', sa.String(length=200), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_doc_status_created', 'rag_documents', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_rag_documents_created_at'), 'rag_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_documents_document_hash'), 'rag_documents', ['document_hash'], unique=True)
    op.create_index(op.f('ix_rag_documents_id'), 'rag_documents', ['id'], unique=False)
    op.create_index(op.f('ix_rag_documents_index_name'), 'rag_documents', ['index_name'], unique=False)
    op.create_index(op.f('ix_rag_documents_status'), 'rag_documents', ['status'], unique=False)
    op.create_table('rag_index_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=200), nullable=False),
    sa.Column('index_type', sa.String(length=50), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('total_vectors', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('build_time_seconds', sa.Float(), nullable=True),
    sa.Column('index_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_rebuild_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_index_metadata_id'), 'rag_index_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_rag_index_metadata_index_name'), 'rag_index_metadata', ['index_name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('certification_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cout_unitaire', sa.Float(), nullable=True),
    sa.Column('stock_actuel', sa.Integer(), nullable=True),
    sa.Column('seuil_alerte', sa.Integer(), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('fournisseur', sa.String(length=200), nullable=True),
    sa.Column('delai_livraison', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_id'), 'spare_parts', ['id'], unique=False)
    op.create_index(op.f('ix_spare_parts_reference'), 'spare_parts', ['reference'], unique=True)
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('taux_horaire', sa.Float(), nullable=True),
    sa.Column('niveau_competence', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', name='technicianstatus'), nullable=False),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_index(op.f('ix_technicians_email'), 'technicians', ['email'], unique=True)
    op.create_index(op.f('ix_technicians_id'), 'technicians', ['id'], unique=False)
    op.create_table('equipment_required_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_proficiency_level', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equipment_skills', 'equipment_required_skills', ['equipment_id', 'skill_id'], unique=False)
    op.create_index(op.f('ix_equipment_required_skills_equipment_id'), 'equipment_required_skills', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_required_skills_id'), 'equipment_required_skills', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_required_skills_skill_id'), 'equipment_required_skills', ['skill_id'], unique=False)
    op.create_table('failure_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('mode_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('failure_cause', sa.Text(), nullable=True),
    sa.Column('failure_effect', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=200), nullable=True),
    sa.Column('prevention_action', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_failure_mode_equipment', 'failure_modes', ['equipment_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_failure_modes_equipment_id'), 'failure_modes', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_failure_modes_id'), 'failure_modes', ['id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('type_panne', sa.String(length=100), nullable=True),
    sa.Column('categorie_panne', sa.String(length=100), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('organe', sa.String(length=200), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('date_intervention', sa.Date(), nullable=False),
    sa.Column('resume_intervention', sa.Text(), nullable=True),
    sa.Column('resultat', sa.Text(), nullable=True),
    sa.Column('duree_arret', sa.Float(), nullable=True),
    sa.Column('cout_materiel', sa.Float(), nullable=True),
    sa.Column('cout_main_oeuvre', sa.Float(), nullable=True),
    sa.Column('cout_total', sa.Float(), nullable=True),
    sa.Column('nombre_heures_mo', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CLOSED', 'CANCELLED', name='interventionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intervention_date_type', 'interventions', ['date_intervention', 'type_panne'], unique=False)
    op.create_index('idx_intervention_equipment_date', 'interventions', ['equipment_id', 'date_intervention'], unique=False)
    op.create_index(op.f('ix_interventions_date_demande'), 'interventions', ['date_demande'], unique=False)
    op.create_index(op.f('ix_interventions_date_intervention'), 'interventions', ['date_intervention'], unique=False)
    op.create_index(op.f('ix_interventions_equipment_id'), 'interventions', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_index(op.f('ix_interventions_status'), 'interventions', ['status'], unique=False)
    op.create_index(op.f('ix_interventions_type_panne'), 'interventions', ['type_panne'], unique=False)
    op.create_table('rag_document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(length=200), nullable=True),
    sa.Column('embedding_cached', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_chunk_doc_index', 'rag_document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_rag_document_chunks_chunk_hash'), 'rag_document_chunks', ['chunk_hash'], unique=False)
    op.create_index(op.f('ix_rag_document_chunks_document_id'), 'rag_document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_document_chunks_id'), 'rag_document_chunks', ['id'], unique=False)
    op.create_table('rag_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_sources', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('retrieval_time_ms', sa.Float(), nullable=True),
    sa.Column('generation_time_ms', sa.Float(), nullable=True),
    sa.Column('total_time_ms', sa.Float(), nullable=True),
    sa.Column('chunks_retrieved', sa.Integer(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('cache_key', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_query_cache', 'rag_queries', ['query_hash', 'cache_hit'], unique=False)
    op.create_index('idx_rag_query_created', 'rag_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_queries_created_at'), 'rag_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_queries_document_id'), 'rag_queries', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_queries_id'), 'rag_queries', ['id'], unique=False)
    op.create_index(op.f('ix_rag_queries_query_hash'), 'rag_queries', ['query_hash'], unique=False)
    op.create_table('technician_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.Column('certification_expiry', sa.Date(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validated_by', sa.String(length=100), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_technician_skills', 'technician_skills', ['technician_id', 'skill_id'], unique=False)
    op.create_index(op.f('ix_technician_skills_id'), 'technician_skills', ['id'], unique=False)
    op.create_index(op.f('ix_technician_skills_skill_id'), 'technician_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_technician_skills_technician_id'), 'technician_skills', ['technician_id'], unique=False)
    op.create_table('intervention_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('cout_unitaire', sa.Float(), nullable=True),
    sa.Column('cout_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intervention_parts', 'intervention_parts', ['intervention_id', 'spare_part_id'], unique=False)
    op.create_index(op.f('ix_intervention_parts_id'), 'intervention_parts', ['id'], unique=False)
    op.create_index(op.f('ix_intervention_parts_intervention_id'), 'intervention_parts', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_intervention_parts_spare_part_id'), 'intervention_parts', ['spare_part_id'], unique=False)
    op.create_table('rpn_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('failure_mode_id', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.Integer(), nullable=False),
    sa.Column('occurrence', sa.Integer(), nullable=False),
    sa.Column('detection', sa.Integer(), nullable=False),
    sa.Column('rpn_value', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('action_status', sa.String(length=50), nullable=True),
    sa.Column('action_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rpn_failure_mode_date', 'rpn_analyses', ['failure_mode_id', 'analysis_date'], unique=False)
    op.create_index('idx_rpn_value_date', 'rpn_analyses', ['rpn_value', 'analysis_date'], unique=False)
    op.create_index(op.f('ix_rpn_analyses_analysis_date'), 'rpn_analyses', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_rpn_analyses_failure_mode_id'), 'rpn_analyses', ['failure_mode_id'], unique=False)
    op.create_index(op.f('ix_rpn_analyses_id'), 'rpn_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_rpn_analyses_rpn_value'), 'rpn_analyses', ['rpn_value'], unique=False)
    op.create_table('technician_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('nombre_heures', sa.Float(), nullable=False),
    sa.Column('taux_horaire', sa.Float(), nullable=True),
    sa.Column('cout_main_oeuvre', sa.Float(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_technician_assignments', 'technician_assignments', ['intervention_id', 'technician_id'], unique=False)
    op.create_index(op.f('ix_technician_assignments_id'), 'technician_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_technician_assignments_intervention_id'), 'technician_assignments', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_technician_assignments_technician_id'), 'technician_assignments', ['technician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technician_assignments_technician_id'), table_name='technician_assignments')
    op.drop_index(op.f('ix_technician_assignments_intervention_id'), table_name='technician_assignments')
    op.drop_index(op.f('ix_technician_assignments_id'), table_name='technician_assignments')
    op.drop_index('idx_technician_assignments', table_name='technician_assignments')
    op.drop_table('technician_assignments')
    op.drop_index(op.f('ix_rpn_analyses_rpn_value'), table_name='rpn_analyses')
    op.drop_index(op.f('ix_rpn_analyses_id'), table_name='rpn_analyses')
    op.drop_index(op.f('ix_rpn_analyses_failure_mode_id'), table_name='rpn_analyses')
    op.drop_index(op.f('ix_rpn_analyses_analysis_date'), table_name='rpn_analyses')
    op.drop_index('idx_rpn_value_date', table_name='rpn_analyses')
    op.drop_index('idx_rpn_failure_mode_date', table_name='rpn_analyses')
    op.drop_table('rpn_analyses')
    op.drop_index(op.f('ix_intervention_parts_spare_part_id'), table_name='intervention_parts')
    op.drop_index(op.f('ix_intervention_parts_intervention_id'), table_name='intervention_parts')
    op.drop_index(op.f('ix_intervention_parts_id'), table_name='intervention_parts')
    op.drop_index('idx_intervention_parts', table_name='intervention_parts')
    op.drop_table('intervention_parts')
    op.drop_index(op.f('ix_technician_skills_technician_id'), table_name='technician_skills')
    op.drop_index(op.f('ix_technician_skills_skill_id'), table_name='technician_skills')
    op.drop_index(op.f('ix_technician_skills_id'), table_name='technician_skills')
    op.drop_index('idx_technician_skills', table_name='technician_skills')
    op.drop_table('technician_skills')
    op.drop_index(op.f('ix_rag_queries_query_hash'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_id'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_document_id'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_created_at'), table_name='rag_queries')
    op.drop_index('idx_rag_query_created', table_name='rag_queries')
    op.drop_index('idx_rag_query_cache', table_name='rag_queries')
    op.drop_table('rag_queries')
    op.drop_index(op.f('ix_rag_document_chunks_id'), table_name='rag_document_chunks')
    op.drop_index(op.f('ix_rag_document_chunks_document_id'), table_name='rag_document_chunks')
    op.drop_index(op.f('ix_rag_document_chunks_chunk_hash'), table_name='rag_document_chunks')
    op.drop_index('idx_rag_chunk_doc_index', table_name='rag_document_chunks')
    op.drop_table('rag_document_chunks')
    op.drop_index(op.f('ix_interventions_type_panne'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_status'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_equipment_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_date_intervention'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_date_demande'), table_name='interventions')
    op.drop_index('idx_intervention_equipment_date', table_name='interventions')
    op.drop_index('idx_intervention_date_type', table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_failure_modes_id'), table_name='failure_modes')
    op.drop_index(op.f('ix_failure_modes_equipment_id'), table_name='failure_modes')
    op.drop_index('idx_failure_mode_equipment', table_name='failure_modes')
    op.drop_table('failure_modes')
    op.drop_index(op.f('ix_equipment_required_skills_skill_id'), table_name='equipment_required_skills')
    op.drop_index(op.f('ix_equipment_required_skills_id'), table_name='equipment_required_skills')
    op.drop_index(op.f('ix_equipment_required_skills_equipment_id'), table_name='equipment_required_skills')
    op.drop_index('idx_equipment_skills', table_name='equipment_required_skills')
    op.drop_table('equipment_required_skills')
    op.drop_index(op.f('ix_technicians_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_email'), table_name='technicians')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_spare_parts_reference'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_id'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_rag_index_metadata_index_name'), table_name='rag_index_metadata')
    op.drop_index(op.f('ix_rag_index_metadata_id'), table_name='rag_index_metadata')
    op.drop_table('rag_index_metadata')
    op.drop_index(op.f('ix_rag_documents_status'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_index_name'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_document_hash'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_created_at'), table_name='rag_documents')
    op.drop_index('idx_rag_doc_status_created', table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('ix_import_logs_import_type'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_created_at'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_designation'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###